SET C51INC=C:\Keil_v5_c51\C51\Inc;C:\Keil_v5_c51\C51\Inc\Atmel
SET C51LIB=C:\Keil_v5_c51\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"C:\Keil_v5_c51\C51\BIN\C51.EXE" @".\Objects\main.__i"
"C:\Keil_v5_c51\C51\BIN\C51.EXE" @".\Objects\iic.__i"
"C:\Keil_v5_c51\C51\BIN\BL51.EXE" @".\Objects\1306.lnp"
"C:\Keil_v5_c51\C51\BIN\OH51.EXE" ".\Objects\1306" 
